export const routes = {
  loginPage: "/login",
  singupPage: "/signup",
  forgotPasswordPage: "/forgotpassword",
  routeMapPage: "/routemap",
  resultsPage: "/results/:departureIdAsString/:destinationIdAsString/:departureDateAsString/:returnDateAsString?",
  tripPage: "/trip/:tripId",
  planYourJourneyPage: "/planyourjourney",
  servicesPage: "/services",
  companyPage: "/company",
  newsletterPage: "/newsletter",
  sendFeedbackPage: "/sendfeedback",
  helpPage: "/help",
  mainPage: "/",
}