export const routes = {
  loginPage: "/login",
  signupPage: "/signup",
  forgotPasswordPage: "/forgotpassword",
  routeMapPage: "/routemap",
  resultsPage: "/results/:departureIdFromUrl/:destinationIdFromUrl/:departureDateAsString/:returnDateAsString?",
  servicesPage: "/services",
  companyPage: "/company",
  newsletterPage: "/newsletter",
  sendFeedbackPage: "/sendfeedback",
  helpPage: "/help",
  checkoutPage: "/checkout",
  profilePage: "/profile",
  yourTripsPage: "/yourtrips",
  mainPage: "/",
}